version: '2'

services:
  test:
    image: ${DOCKER_REGISTRY}test
    build:
      context: .
      dockerfile: Test/Dockerfile
    ports: 
     - 11225:5000
    links:
     - mongo
    depends_on:
     - redis
     - mongo
  mongo:
    image: mongo
    ports:
     - 27017:27017
  redis:
    image: redis
    ports:
     - 6379:6379
      
